#!/usr/bin/env bash
# Infinity Loop - Generated by: ca loop
# Date: 2026-03-29T03:12:25+02:00
# Autonomously processes beads epics via Claude Code sessions.
#
# Usage:
#   ./infinity-loop.sh
#   LOOP_DRY_RUN=1 ./infinity-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_RETRIES=1
MODEL='claude-opus-4-6[1m]'
EPIC_IDS='long-running-harness-ba9 long-running-harness-3tn long-running-harness-wzc long-running-harness-wjm long-running-harness-kza'
LOG_DIR="agent_logs"
MIN_FREE_MEMORY_PCT=${MIN_FREE_MEMORY_PCT:-20}  # Stop loop if free memory drops below this %
WATCHDOG_THRESHOLD=${WATCHDOG_THRESHOLD:-15}     # Kill session if free memory drops below this %
WATCHDOG_INTERVAL=${WATCHDOG_INTERVAL:-30}       # Seconds between watchdog checks

# Helpers
timestamp() { date '+%Y-%m-%d_%H-%M-%S'; }
# log() writes to stderr so it never corrupts command-substitution captures
log() { echo "[$(timestamp)] $*" >&2; }
die() { log "FATAL: $*"; exit 1; }

command -v claude >/dev/null || die "claude CLI required"
command -v bd >/dev/null || die "bd (beads) CLI required"

# Detect JSON parser: prefer jq, fall back to python3
HAS_JQ=false
command -v jq >/dev/null 2>&1 && HAS_JQ=true
if [ "$HAS_JQ" = false ]; then
  command -v python3 >/dev/null 2>&1 || die "jq or python3 required for JSON parsing"
fi

mkdir -p "$LOG_DIR"

# Crash handler: log WHY we died and update status file
_loop_cleanup() {
  local exit_code=$?
  stop_memory_watchdog 2>/dev/null || true
  if [ $exit_code -ne 0 ]; then
    log "CRASH: Script exited with code $exit_code at line ${BASH_LINENO[0]:-unknown}"
    echo "{\"status\":\"crashed\",\"exit_code\":$exit_code,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"line\":\"${BASH_LINENO[0]:-unknown}\"}" > "${LOG_DIR:-.}/.loop-status.json" 2>/dev/null || true
  fi
}
trap _loop_cleanup EXIT

# --- Memory Safety (3-Layer Defense) ---

# cleanup_orphans() - Kill leftover test/build processes from THIS repo between sessions
# Scoped to current working directory to avoid killing unrelated processes
cleanup_orphans() {
  local killed=0
  local repo_dir
  repo_dir=$(pwd)
  for pid in $(pgrep -f "vitest|node.*\.test\.|go\.test|pytest|cargo\.test" 2>/dev/null || true); do
    local proc_cwd=""
    if [ "$(uname)" = "Darwin" ]; then
      proc_cwd=$(lsof -p "$pid" -Fn 2>/dev/null | grep '^ncwd' | sed 's/^n//' || true)
    else
      proc_cwd=$(readlink "/proc/$pid/cwd" 2>/dev/null || true)
    fi
    # Only kill if the process cwd is exactly this repo or a subdirectory
    case "$proc_cwd" in
      "$repo_dir"|"$repo_dir"/*) kill "$pid" 2>/dev/null && killed=$((killed + 1)) ;;
    esac
  done
  if [ "$killed" -gt 0 ]; then
    log "Cleaned up $killed orphan test processes"
    sleep 2  # Let OS reclaim memory
  fi
}

# get_memory_pct() - Return current free memory percentage on stdout (empty on failure)
get_memory_pct() {
  if [ "$(uname)" = "Darwin" ]; then
    memory_pressure 2>/dev/null | awk -F: '/free percentage/ {gsub(/%| /,"",$2); print $2}'
  else
    local mem_total mem_available
    mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)
    mem_available=$(awk '/MemAvailable/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)
    if [ "$mem_total" -gt 0 ]; then
      echo $(( mem_available * 100 / mem_total ))
    fi
  fi
}

# check_memory() - Abort if system free memory is too low
check_memory() {
  local free_pct
  free_pct=$(get_memory_pct)
  if [ -z "$free_pct" ]; then
    return 0  # Can't measure, assume OK
  fi
  if [ "$free_pct" -lt "$MIN_FREE_MEMORY_PCT" ]; then
    log "WARN: System memory ${free_pct}% free (minimum: ${MIN_FREE_MEMORY_PCT}%)"
    return 1
  fi
  log "Memory OK: ${free_pct}% free"
  return 0
}

# start_memory_watchdog() - Background monitor that kills target PID on memory pressure
# Args: $1=PID to kill, $2=log file for memory stats
# Sets: WATCHDOG_PID (global)
WATCHDOG_PID=""

start_memory_watchdog() {
  local target_pid="$1"
  local mem_log="$2"
  (
    while kill -0 "$target_pid" 2>/dev/null; do
      local pct
      pct=$(get_memory_pct)
      if [ -n "$pct" ]; then
        echo "[$(date '+%Y-%m-%d_%H-%M-%S')] memory_free=${pct}%" >> "$mem_log"
        if [ "$pct" -lt "$WATCHDOG_THRESHOLD" ]; then
          echo "[$(date '+%Y-%m-%d_%H-%M-%S')] WATCHDOG: memory ${pct}% < ${WATCHDOG_THRESHOLD}%, killing PID $target_pid" >> "$mem_log"
          kill -TERM -- -"$target_pid" 2>/dev/null || kill "$target_pid" 2>/dev/null || true
          exit 0
        fi
      fi
      sleep "$WATCHDOG_INTERVAL"
    done
  ) &
  WATCHDOG_PID=$!
}

stop_memory_watchdog() {
  if [ -n "$WATCHDOG_PID" ]; then
    kill "$WATCHDOG_PID" 2>/dev/null || true
    wait "$WATCHDOG_PID" 2>/dev/null || true
    WATCHDOG_PID=""
  fi
}

# --- JSON Parsing ---
# parse_json() - extract a value from JSON stdin
# Uses jq (primary) with python3 fallback
# Auto-unwraps single-element arrays (bd show --json returns [...])
# Usage: echo '[{"status":"open"}]' | parse_json '.status'
parse_json() {
  local filter="$1"
  if [ "$HAS_JQ" = true ]; then
    jq -r "if type == \"array\" then .[0] else . end | $filter"
  else
    python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
f = sys.argv[1].strip('.')
parts = [p for p in f.split('.') if p]
v = data
try:
    for p in parts:
        v = v[p]
except (KeyError, IndexError, TypeError):
    v = None
print('' if v is None else v)
" "$filter"
  fi
}

# --- Epic Selector ---

# check_deps_closed() - Verify all depends_on for an epic are closed
# Returns 0 if all deps closed (or no deps), 1 if any dep is open
check_deps_closed() {
  local epic_id="$1"
  local deps_json
  deps_json=$(bd show "$epic_id" --json 2>/dev/null || echo "")
  if [ -z "$deps_json" ]; then
    return 0
  fi
  local blocking_dep
  if [ "$HAS_JQ" = true ]; then
    blocking_dep=$(echo "$deps_json" | jq -r '
      if type == "array" then .[0] else . end |
      (.depends_on // .dependencies // []) |
      map(select(.status != "closed")) |
      .[0].id // empty
    ' 2>/dev/null || echo "")
  else
    blocking_dep=$(echo "$deps_json" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
deps = data.get('depends_on', data.get('dependencies', []))
for d in deps:
    s = d.get('status', 'open') if isinstance(d, dict) else 'open'
    if s != 'closed':
        print(d.get('id', d) if isinstance(d, dict) else d)
        break
" 2>/dev/null || echo "")
  fi
  if [ -n "$blocking_dep" ]; then
    log "Skip $epic_id: blocked by dependency $blocking_dep (not closed)"
    return 1
  fi
  return 0
}

get_next_epic() {
  if [ -n "$EPIC_IDS" ]; then
    for epic_id in $EPIC_IDS; do
      case " $PROCESSED " in (*" $epic_id "*) continue ;; esac
      local status
      status=$(bd show "$epic_id" --json 2>/dev/null | parse_json '.status' 2>/dev/null || echo "")
      if [ "$status" = "open" ]; then
        check_deps_closed "$epic_id" || continue
        echo "$epic_id"
        return 0
      fi
    done
    return 1
  else
    local epic_id
    if [ "$HAS_JQ" = true ]; then
      epic_id=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | jq -r '.[].id' 2>/dev/null | while read -r id; do
        case " $PROCESSED " in (*" $id "*) continue ;; esac
        check_deps_closed "$id" || continue
        echo "$id"
        break
      done)
    else
      local candidates
      candidates=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | python3 -c "
import sys, json
processed = set(sys.argv[1].split())
items = json.load(sys.stdin)
for item in items:
    if item['id'] not in processed:
        print(item['id'])" "$PROCESSED" 2>/dev/null || echo "")
      for cid in $candidates; do
        check_deps_closed "$cid" || continue
        epic_id="$cid"
        break
      done
    fi
    if [ -z "$epic_id" ]; then
      return 1
    fi
    echo "$epic_id"
    return 0
  fi
}

# --- Prompt Builder ---
build_prompt() {
  local epic_id="$1"
  cat <<'PROMPT_HEADER'
You are running in an autonomous infinity loop. Your task is to fully implement a beads epic.

## Step 1: Load context
Run these commands to prime your session:
PROMPT_HEADER
  cat <<PROMPT_BODY
\`\`\`bash
npx ca load-session
bd show $epic_id
\`\`\`

Read the epic details carefully. Understand scope, acceptance criteria, and sub-tasks.

## Step 2: Execute the workflow
Run the full compound workflow for this epic, starting from the plan phase
(spec-dev is already done -- the epic exists):

/compound:cook-it from plan -- Epic: $epic_id

Work through all phases: plan, work, review, compound.

## Step 3: On completion
When all work is done and tests pass:
1. Close the epic: \`bd close $epic_id\`
2. Commit and push all changes
3. Output this exact marker on its own line:

EPIC_COMPLETE

## Step 4: On failure
If you cannot complete the epic after reasonable effort:
1. Add a note: \`bd update $epic_id --notes "Loop failed: <reason>"\`
2. Output this exact marker on its own line:

EPIC_FAILED

## Step 5: On human required
If you hit a blocker that REQUIRES human action (account creation, API keys,
external service setup, design decisions you cannot make, etc.):
1. Add a note: \`bd update $epic_id --notes "Human required: <reason>"\`
2. Output this exact marker followed by a short reason on the SAME line:

HUMAN_REQUIRED: <reason>

Example: HUMAN_REQUIRED: Need AWS credentials configured in .env

## Memory Safety Rules
- For Go work, use \`go test -tags sqlite_fts5 ./...\` in the go/ directory.
- NEVER run embedding tests unless the epic modifies embedding code.
- Between test runs, wait for all child processes to exit before starting another.

## Rules
- Do NOT ask questions -- there is no human. Make reasonable decisions.
- Do NOT stop early -- complete the full workflow.
- If tests fail, fix them. Retry up to 3 times before declaring failure.
- Use HUMAN_REQUIRED only for true blockers that no amount of retrying can solve.
- Commit incrementally as you make progress.
PROMPT_BODY
}

# --- Text Extractor ---
# extract_text() - Extract assistant text from stream-json events on stdin
# Claude Code stream-json: {"type":"assistant","message":{"content":[{"type":"text","text":"..."}]}}
extract_text() {
  if [ "$HAS_JQ" = true ]; then
    jq -j --unbuffered '
      select(.type == "assistant") |
      .message.content[]? |
      select(.type == "text") |
      .text // empty
    ' 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  else
    python3 -c "
import sys, json
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    try:
        obj = json.loads(line)
        if obj.get('type') == 'assistant':
            for block in obj.get('message', {}).get('content', []):
                if block.get('type') == 'text':
                    text = block.get('text', '')
                    if text:
                        print(text, end='', flush=True)
    except (json.JSONDecodeError, KeyError, TypeError):
        pass
" 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  fi
}

# --- Marker Detection ---
# detect_marker() - Check for completion markers in log and trace
# Primary: macro log (anchored patterns). Fallback: trace JSONL (unanchored).
# Returns: "complete", "failed", "human:<reason>", or "none"
detect_marker() {
  local logfile="$1" tracefile="$2"

  # Primary: check extracted text with anchored patterns
  if [ -s "$logfile" ]; then
    if grep -q "^EPIC_COMPLETE$" "$logfile"; then
      echo "complete"; return 0
    elif grep -q "^HUMAN_REQUIRED:" "$logfile"; then
      local reason
      reason=$(grep "^HUMAN_REQUIRED:" "$logfile" | head -1 | sed 's/^HUMAN_REQUIRED: *//')
      echo "human:$reason"; return 0
    elif grep -q "^EPIC_FAILED$" "$logfile"; then
      echo "failed"; return 0
    fi
  fi

  # Fallback: check raw trace JSONL (unanchored -- markers are inside JSON strings)
  if [ -s "$tracefile" ]; then
    if grep -q "EPIC_COMPLETE" "$tracefile"; then
      echo "complete"; return 0
    elif grep -q "HUMAN_REQUIRED:" "$tracefile"; then
      echo "human:detected in trace"; return 0
    elif grep -q "EPIC_FAILED" "$tracefile"; then
      echo "failed"; return 0
    fi
  fi

  echo "none"
}

# --- Observability ---
STATUS_FILE="$LOG_DIR/.loop-status.json"
EXEC_LOG="$LOG_DIR/loop-execution.jsonl"

write_status() {
  local status="$1"
  local epic_id="${2:-}"
  local attempt="${3:-0}"
  if [ "$status" = "idle" ]; then
    echo "{\"status\":\"idle\",\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$STATUS_FILE"
  else
    echo "{\"epic_id\":\"$epic_id\",\"attempt\":$attempt,\"started_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"status\":\"$status\"}" > "$STATUS_FILE"
  fi
}

log_result() {
  local epic_id="$1" result="$2" attempts="$3" duration="$4"
  echo "{\"epic_id\":\"$epic_id\",\"result\":\"$result\",\"attempts\":$attempts,\"duration_s\":$duration,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" >> "$EXEC_LOG"
}

# --- Main Loop ---
COMPLETED=0
FAILED_COUNT=0
SKIPPED=0
PROCESSED=""
LOOP_START=$(date +%s)

log "=========================================="
log "Infinity loop starting"
log "=========================================="
log "Config: max_retries=$MAX_RETRIES model=$MODEL"
[ -n "$EPIC_IDS" ] && log "Targeting epics: $EPIC_IDS" || log "Targeting: all ready epics"

while true; do
  # Memory safety: clean up orphans and check memory before starting next epic
  cleanup_orphans
  if ! check_memory; then
    log "FATAL: Memory pressure too high, stopping loop to prevent system freeze"
    log "  Hint: set MIN_FREE_MEMORY_PCT (current: ${MIN_FREE_MEMORY_PCT}%) or kill background processes"
    FAILED_COUNT=$((FAILED_COUNT + 1))
    break
  fi

  EPIC_ID=$(get_next_epic) || break

  log "=========================================="
  log "Processing epic: $EPIC_ID"
  log "=========================================="
  EPIC_START=$(date +%s)

  ATTEMPT=0
  SUCCESS=false

  write_status "running" "$EPIC_ID" 1

  while [ $ATTEMPT -le $MAX_RETRIES ]; do
    ATTEMPT=$((ATTEMPT + 1))
    TS=$(timestamp)
    LOGFILE="$LOG_DIR/loop_$EPIC_ID-$TS.log"
    TRACEFILE="$LOG_DIR/trace_$EPIC_ID-$TS.jsonl"

    write_status "running" "$EPIC_ID" "$ATTEMPT"

    # Update .latest symlink for ca watch (before claude invocation so watch can discover it)
    ln -sf "$(basename "$TRACEFILE")" "$LOG_DIR/.latest"

    log "Attempt $ATTEMPT/$((MAX_RETRIES + 1)) for $EPIC_ID (log: $LOGFILE)"

    if [ -n "${LOOP_DRY_RUN:-}" ]; then
      log "[DRY RUN] Would run claude session for $EPIC_ID"
      SUCCESS=true
      break
    fi

    PROMPT=$(build_prompt "$EPIC_ID")

    # Two-scope logging: stream-json to trace JSONL, extracted text to macro log
    # Run in background subshell so we can track PID for the memory watchdog
    MEM_LOG="$LOG_DIR/memory_${EPIC_ID}-${TS}.log"
    (
      claude --dangerously-skip-permissions \
             --permission-mode auto \
             --model "$MODEL" \
             --output-format stream-json \
             --verbose \
             -p "$PROMPT" \
             2>"$LOGFILE.stderr" | tee "$TRACEFILE" | extract_text > "$LOGFILE"
    ) &
    CLAUDE_PGID=$!
    start_memory_watchdog "$CLAUDE_PGID" "$MEM_LOG"
    wait "$CLAUDE_PGID" 2>/dev/null || true
    stop_memory_watchdog

    # Detect if watchdog killed the session
    if [ -f "$MEM_LOG" ] && grep -q "WATCHDOG:" "$MEM_LOG" 2>/dev/null; then
      log "WARN: Session killed by memory watchdog (see $MEM_LOG)"
      cleanup_orphans
    fi

    # Append stderr to macro log
    [ -f "$LOGFILE.stderr" ] && cat "$LOGFILE.stderr" >> "$LOGFILE" && rm -f "$LOGFILE.stderr"

    # Health check: warn if macro log extraction failed
    if [ -s "$TRACEFILE" ] && [ ! -s "$LOGFILE" ]; then
      log "WARN: Macro log is empty but trace has content (extract_text may have failed)"
    fi

    MARKER=$(detect_marker "$LOGFILE" "$TRACEFILE")
    case "$MARKER" in
      (complete)
        log "Epic $EPIC_ID completed successfully"
        SUCCESS=true
        break
        ;;
      (human:*)
        REASON="${MARKER#human:}"
        log "Epic $EPIC_ID needs human action: $REASON"
        bd update "$EPIC_ID" --notes "Human required: $REASON" 2>/dev/null || true
        SUCCESS=skip
        break
        ;;
      (failed)
        log "Epic $EPIC_ID reported failure (attempt $ATTEMPT)"
        ;;
      (*)
        log "Epic $EPIC_ID session ended without marker (attempt $ATTEMPT)"
        ;;
    esac

    if [ $ATTEMPT -le $MAX_RETRIES ]; then
      log "Retrying $EPIC_ID..."
      cleanup_orphans
      sleep 5
    fi
  done

  EPIC_DURATION=$(( $(date +%s) - EPIC_START ))

  if [ "$SUCCESS" = true ]; then
    if [ -z "${LOOP_DRY_RUN:-}" ]; then
    # Verify working tree is clean after epic completion
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
      log "WARN: Working tree dirty after epic completion, auto-committing"
      git add -A && git commit -m "chore: auto-commit uncommitted changes from $EPIC_ID" 2>/dev/null || true
    fi
    COMPLETED=$((COMPLETED + 1))
    log_result "$EPIC_ID" "complete" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID done. Completed so far: $COMPLETED"

    fi
  elif [ "$SUCCESS" = skip ]; then
    SKIPPED=$((SKIPPED + 1))
    log_result "$EPIC_ID" "skipped" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID skipped (human required). Continuing."
  else
    FAILED_COUNT=$((FAILED_COUNT + 1))
    log_result "$EPIC_ID" "failed" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID failed after $((MAX_RETRIES + 1)) attempts. Stopping loop."
    PROCESSED="$PROCESSED $EPIC_ID"
    break
  fi

  PROCESSED="$PROCESSED $EPIC_ID"
done


TOTAL_DURATION=$(( $(date +%s) - LOOP_START ))

if [ -z "${LOOP_DRY_RUN:-}" ]; then
echo "{\"type\":\"summary\",\"completed\":$COMPLETED,\"failed\":$FAILED_COUNT,\"skipped\":$SKIPPED,\"total_duration_s\":$TOTAL_DURATION}" >> "$EXEC_LOG"
write_status "idle"

# Push to remote if available
if git remote get-url origin >/dev/null 2>&1; then
  log "Pushing to remote..."
  git push 2>&1 || log "WARN: git push failed (check SSH/auth)"
fi
fi

log "=========================================="
log "Loop finished"
log "  Completed: $COMPLETED"
log "  Failed:    $FAILED_COUNT"
log "  Skipped:   $SKIPPED"
log "  Duration:  ${TOTAL_DURATION}s ($(( TOTAL_DURATION / 60 ))m)"
log "  Processed: $PROCESSED"
log "=========================================="
[ $FAILED_COUNT -eq 0 ] && exit 0 || exit 1
