#!/usr/bin/env bash
# Polish Loop - Generated by: ca polish
# Date: 2026-03-28T13:46:02+01:00
# Iterates N cycles of: audit fleet -> polish architect -> inner infinity loop
#
# Usage:
#   ./polish-loop.sh
#   POLISH_DRY_RUN=1 ./polish-loop.sh  # Preview without executing

set -euo pipefail

# Config
CYCLES=5
MODEL='claude-opus-4-6[1m]'
META_EPIC='long-running-harness-kno'
SPEC_FILE='docs/specs/brutalwav-daw.md'
CONFIGURED_REVIEWERS='claude-sonnet claude-opus gemini codex'
LOG_DIR="agent_logs"
REVIEW_TIMEOUT=${REVIEW_TIMEOUT:-600}

mkdir -p "$LOG_DIR"

# --- Logging ---
log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] [polish] $*" >&2
}

# --- Crash Handler ---
_polish_cleanup() {
  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    log "Polish loop crashed with exit code $exit_code at line ${BASH_LINENO[0]:-unknown}"
    echo "{\"status\":\"crashed\",\"exit_code\":$exit_code,\"cycle\":${cycle:-0},\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"line\":\"${BASH_LINENO[0]:-unknown}\"}" > "$LOG_DIR/.polish-status.json"
    exit $exit_code
  fi
}
trap _polish_cleanup EXIT

# --- Portable Timeout ---
# GNU timeout -> gtimeout (macOS Homebrew) -> shell fallback
portable_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then
    timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then
    gtimeout "$secs" "$@"
  else
    "$@" &
    local pid=$!
    ( sleep "$secs" && kill "$pid" 2>/dev/null ) &
    local watchdog=$!
    wait "$pid" 2>/dev/null
    local rc=$?
    kill "$watchdog" 2>/dev/null
    wait "$watchdog" 2>/dev/null
    return $rc
  fi
}

# --- Prerequisites ---
command -v claude >/dev/null 2>&1 || { echo "ERROR: claude CLI not found"; exit 1; }
command -v bd >/dev/null 2>&1 || { echo "ERROR: bd CLI not found"; exit 1; }
command -v npx >/dev/null 2>&1 || { echo "ERROR: npx not found (needed for inner loop)"; exit 1; }
[ -f "$SPEC_FILE" ] || { log "ERROR: spec file not found: $SPEC_FILE"; exit 1; }

# --- Reviewer Detection ---
detect_polish_reviewers() {
  AVAILABLE_REVIEWERS=""
  for reviewer in $CONFIGURED_REVIEWERS; do
    local cli_name
    case "$reviewer" in
      (claude-sonnet|claude-opus) cli_name="claude" ;;
      (gemini)                    cli_name="gemini" ;;
      (codex)                     cli_name="codex" ;;
      (*) log "WARN: unknown reviewer $reviewer"; continue ;;
    esac
    if ! command -v "$cli_name" >/dev/null 2>&1; then
      log "WARN: $reviewer configured but $cli_name CLI not found -- skipping"
      continue
    fi
    if ! portable_timeout 10 "$cli_name" --version >/dev/null 2>&1; then
      log "WARN: $reviewer configured but $cli_name health check failed -- skipping"
      continue
    fi
    AVAILABLE_REVIEWERS="$AVAILABLE_REVIEWERS $reviewer"
  done
  AVAILABLE_REVIEWERS="${AVAILABLE_REVIEWERS# }"
  if [ -z "$AVAILABLE_REVIEWERS" ]; then
    log "ERROR: no reviewer CLIs available"
    exit 1
  fi
  log "Available reviewers: $AVAILABLE_REVIEWERS"
}

# --- Audit Prompt (Full-Spectrum Quality Audit) ---
build_audit_prompt() {
  local cycle_num="$1"
  local spec_content
  spec_content=$(cat "$SPEC_FILE" 2>/dev/null || echo "(spec file not found)")

  cat <<'AUDIT_PROMPT_EOF'
You are a senior quality auditor performing a holistic review of the ENTIRE implementation.
Audit EVERYTHING -- code, architecture, security, testing, error handling, AND user-facing
quality. This is not just a UI checklist. Every dimension matters.

## Your Task
1. Read the codebase thoroughly (source code, tests, config, docs)
2. Evaluate against ALL sections of the quality checklist below
3. Produce a structured report with P0/P1/P2 findings
4. Tag any finding that requires browser/runtime verification with [NEEDS_QA]

## Full-Spectrum Quality Checklist

### 1. Code Quality and Architecture
- [ ] Clean module boundaries -- no circular dependencies, clear responsibilities
- [ ] Consistent naming conventions across the codebase
- [ ] No dead code, unused imports, or commented-out blocks
- [ ] Functions are focused and short (< 50 lines, single responsibility)
- [ ] No code duplication -- shared logic is properly extracted
- [ ] Error handling is consistent and thorough (no swallowed errors)
- [ ] Logging is meaningful (not too verbose, not silent on failures)
- [ ] Configuration is externalized (no hardcoded URLs, keys, or magic numbers)
- [ ] Data flows are clear and traceable

### 2. Security
- [ ] No secrets or credentials in source code
- [ ] Input validation at all system boundaries (forms, APIs, URL params)
- [ ] SQL/NoSQL injection protection (parameterized queries, ORMs)
- [ ] XSS protection (output encoding, CSP headers)
- [ ] Authentication and authorization checks on all protected routes
- [ ] CORS configured correctly (not wildcard in production)
- [ ] Dependencies are up to date (no known CVEs)
- [ ] Sensitive data not logged or exposed in error messages

### 3. Testing
- [ ] Test coverage is meaningful (not just line count -- tests verify behavior)
- [ ] Edge cases are tested (empty input, boundary values, error paths)
- [ ] No flaky tests (tests pass consistently)
- [ ] Integration tests exist for critical paths
- [ ] Tests are independent (no shared mutable state between tests)
- [ ] Test data is realistic (not trivial "foo"/"bar" stubs)
- [ ] Error scenarios are tested (network failures, invalid data, timeouts)

### 4. Error Handling and Resilience
- [ ] User-facing errors are clear and actionable (not stack traces)
- [ ] Network failures are handled gracefully (retry, fallback)
- [ ] Loading states prevent jank and race conditions (if UI)
- [ ] Partial failures don't crash the whole application
- [ ] Timeouts are configured for external calls
- [ ] Validation errors are specific (not just "invalid input")

### 5. Performance
- [ ] No N+1 queries or excessive API calls
- [ ] No memory leaks (event listeners cleaned up, subscriptions unsubscribed)
- [ ] Assets are optimized -- images, fonts, bundles (if web UI)
- [ ] Lazy loading for below-fold content (if web UI)
- [ ] Core Web Vitals: LCP < 2.5s, INP < 200ms, CLS < 0.1 (if web UI)
- [ ] Font loading strategy -- font-display, preload, size-adjust fallbacks (if web UI)
- [ ] Bundle size is reasonable -- tree-shaking, code splitting (if web UI)

### 6. UI States and Interaction (if applicable)
- [ ] 5 states per data view: loading, empty, error, offline, partial data
- [ ] hover/active/focus/disabled states on interactive elements
- [ ] Press feedback within 100ms
- [ ] Validation feedback is inline and immediate
- [ ] Page transitions are smooth and purposeful

### 7. Visual Craft (if applicable)
- [ ] 3+ levels of typography hierarchy (size, weight, color)
- [ ] Geometric spacing scale (4/8/16/24/32/48/64) -- no arbitrary values
- [ ] Semantic color tokens (not raw hex)
- [ ] Consistent icon style and sizing
- [ ] No borders where spacing, background, or shadow would work

### 8. Responsiveness (if applicable)
- [ ] Mobile is first-class (different IA, content priority, interaction patterns)
- [ ] 44x44px minimum touch targets
- [ ] Fluid typography (clamp or viewport units)
- [ ] No horizontal scroll on any breakpoint

### 9. Accessibility (if applicable)
- [ ] Semantic HTML (not div soup)
- [ ] Color contrast meets WCAG AA (4.5:1 for text)
- [ ] Keyboard navigation works (visible focus indicators)
- [ ] ARIA only where semantic HTML is insufficient
- [ ] prefers-reduced-motion respected

### 10. Common AI Laziness Anti-Patterns
- [ ] NOT shallow implementations -- deep interfaces, not pass-through wrappers
- [ ] NOT generic/placeholder code -- curated, specific, deliberate
- [ ] NOT skipping error paths -- error handling is a first-class feature
- [ ] NOT missing edge cases -- boundary conditions are designed, not discovered
- [ ] NOT flat interactions -- every user action needs feedback
- [ ] NOT arbitrary spacing or magic numbers
- [ ] NOT ignoring mobile/responsive
- [ ] NOT test-after or tests that just assert "it exists"

## Visual Verification (Self-Serve)

Before reviewing code, check whether the project has a runnable UI. You should visually
verify what users actually see, not just read the source.

### Auto-Detection (check in order, stop at first match)
1. package.json with "dev" or "start" script --> npm/pnpm/yarn run dev
   Default ports: vite.config.* (5173), next.config.* (3000), nuxt.config.* (3000), angular.json (4200), svelte.config.* (5173)
2. manage.py --> Django (port 8000)
3. app.py or main.py with Flask/FastAPI imports --> port 5000 or 8000
4. Go main.go with http.ListenAndServe --> port 8080
5. Static index.html without framework --> python3 -m http.server 8000
6. None of the above --> skip visual verification entirely (no UI to screenshot)

### If UI Detected
1. Start the dev server in the background. Wait for HTTP 200 on the root path (poll every 1s, timeout 30s). If the server fails to start within the timeout, skip visual verification and tag visual findings with [NEEDS_QA].
2. Use Playwright (headless Chromium) to take full-page screenshots at 4 viewports:
   - 375px (mobile), 768px (tablet), 1024px (small desktop), 1440px (desktop)
3. Navigate to key routes (up to 10 -- check router config, nav links, or page files) and screenshot each.
4. Critique the screenshots as part of your audit:
   - Layout alignment and spacing consistency across viewports
   - Typography hierarchy and readability (contrast, size, truncation)
   - Responsive behavior (does mobile get a real layout, not shrunken desktop?)
   - Visual states visible on the page (empty states, loading indicators, error handling)
   - Design system consistency (are colors, spacing, and components coherent?)
5. Save screenshots to the cycle directory with descriptive names (e.g., homepage-375.png, mixer-1440.png).
6. Include visual findings in your P0/P1/P2 report with screenshot references as evidence.
7. Stop the dev server when done.

### If Playwright Is Unavailable
If you cannot install or run Playwright, record a P3/INFO finding ("Playwright not available
for visual verification") and skip this section. Tag any visual concern with [NEEDS_QA] so
the polish architect routes it to the QA Engineer for hands-on testing.

### If No UI Detected
Skip this section entirely. Not every project has a visual interface -- APIs, CLIs, and
libraries do not need visual verification. Focus on code quality, testing, and architecture.

## Browser Verification (QA Engineer)

For any finding that requires runtime verification to confirm (visual bugs, interaction
issues, responsive problems, accessibility failures, performance bottlenecks visible at
runtime), tag it with [NEEDS_QA]. The polish architect will route these to the QA Engineer
skill (`.claude/skills/compound/qa-engineer/SKILL.md`) which performs hands-on browser
automation testing: screenshots, exploratory testing, boundary inputs, accessibility checks,
network inspection, and viewport stress testing against the running application.

Examples of [NEEDS_QA] findings:
- "Mobile layout breaks at 375px [NEEDS_QA]"
- "Form validation not visible on submit [NEEDS_QA]"
- "No loading skeleton while data fetches [NEEDS_QA]"
- "Contrast ratio may fail WCAG AA on the dashboard header [NEEDS_QA]"

## Output Format
Structure your report as:

### P0 -- Must Fix (blocks quality)
- Finding description with file/line references (add [NEEDS_QA] if runtime verification needed)

### P1 -- Should Fix (significant quality gap)
- Finding description with file/line references (add [NEEDS_QA] if runtime verification needed)

### P2 -- Nice to Fix (polish opportunity)
- Finding description with file/line references (add [NEEDS_QA] if runtime verification needed)

### Summary
- Overall assessment across all dimensions (1-2 sentences)
- Top 3 highest-impact improvements
- Count of [NEEDS_QA] findings that require browser verification

AUDIT_PROMPT_EOF

  echo ""
  echo "## Spec Context"
  echo "$spec_content"
  echo ""
  echo "## Cycle"
  echo "This is polish cycle $cycle_num of $CYCLES."
}

# --- Spawn Reviewers ---
run_polish_audit() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  mkdir -p "$cycle_dir"

  log "Cycle $cycle_num: building audit prompt"
  local prompt_file="$cycle_dir/audit-prompt.md"
  build_audit_prompt "$cycle_num" > "$prompt_file"

  log "Cycle $cycle_num: spawning reviewers"
  local pids=""
  for reviewer in $AVAILABLE_REVIEWERS; do
    local report="$cycle_dir/$reviewer-report.md"
    local model_name=""

    case "$reviewer" in
      (claude-opus)   model_name="claude-opus-4-6[1m]" ;;
      (claude-sonnet) model_name="claude-sonnet-4-6" ;;
    esac

    if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
      log "DRY RUN: would spawn $reviewer"
      echo "(dry run -- no actual review)" > "$report"
      continue
    fi

    case "$reviewer" in
      (claude-opus|claude-sonnet)
        (portable_timeout "$REVIEW_TIMEOUT" claude --model "$model_name" \
          --dangerously-skip-permissions \
          --permission-mode auto \
          --output-format text \
          -p - < "$prompt_file" > "$report" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
      (gemini)
        (portable_timeout "$REVIEW_TIMEOUT" gemini --yolo \
          < "$prompt_file" \
          > "$report" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
      (codex)
        (portable_timeout "$REVIEW_TIMEOUT" codex exec --full-auto \
          -o "$report" -- - < "$prompt_file" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
    esac
    pids="$pids $!"
    log "Spawned $reviewer (PID $!)"
  done

  log "Waiting for all reviewers to complete"
  for pid in $pids; do wait "$pid" 2>/dev/null || true; done
  log "All reviewers completed for cycle $cycle_num"
}

# --- Synthesize Report ---
synthesize_report() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local report_file="docs/specs/polish-report-cycle-${cycle_num}.md"

  mkdir -p "$(dirname "$report_file")"

  log "Synthesizing polish report for cycle $cycle_num"

  {
    echo "# Polish Report -- Cycle $cycle_num"
    echo ""
    echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    for reviewer in $AVAILABLE_REVIEWERS; do
      local report="$cycle_dir/$reviewer-report.md"
      if [ -s "$report" ]; then
        echo "## $reviewer"
        echo ""
        cat "$report"
        echo ""
      else
        echo "## $reviewer"
        echo ""
        echo "(no output -- reviewer may have crashed or timed out)"
        echo ""
      fi
    done
  } > "$report_file"

  log "Polish report written to $report_file"
  POLISH_REPORT="$report_file"
}

# --- Polish Architect ---
run_polish_architect() {
  local cycle_num="$1"
  local report_file="$2"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local architect_log="$cycle_dir/polish-architect.log"

  log "Cycle $cycle_num: spawning polish architect"

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would spawn polish architect"
    return 0
  fi

  if [ -z "$report_file" ] || [ ! -s "$report_file" ]; then
    log "ERROR: polish report is empty or missing, skipping architect"
    return 1
  fi

  local prompt_file="$cycle_dir/polish-architect-prompt.md"
  {
    cat <<'ARCHITECT_HEADER_EOF'
You are a polish architect. Your job is NOT just to mechanically convert reviewer findings
into tickets. You are here to push the product toward exceptional quality and craft.

## Step 1: Load Context
Prime your session so you understand the product, its vision, and what has been built:

```bash
npx ca load-session
```

Then read the spec file listed under "## Spec File" at the bottom of this prompt to understand the product vision and goals.

Explore the codebase. Understand the current state -- what's built, what's working, what's rough.

## Step 2: Study the Audit Report
Read the polish report below. Reviewer findings are your STARTING POINT, not your ceiling.

## Step 3: Think Ambitiously
Go beyond the findings. Ask yourself:
- What would make a user fall in love with this product?
- Where does the current implementation feel "good enough" but not great?
- What micro-interactions, transitions, or details would elevate the experience?
- Are there rough edges the reviewers missed because they were checking a list?
- Does the product feel cohesive, or like a collection of features?
- Would you be proud to ship this? What would you fix first if not?

The polish loop exists to close the gap between "it works" and "it's exceptional."
Address ALL priority levels -- P0 critical issues, P1 quality gaps, AND P2 polish
opportunities. P2 items are not optional in a polish cycle -- they are the whole point.
Add your own P2/P3 discoveries beyond what reviewers found.

## Step 4: Route QA Findings
Look for [NEEDS_QA] tags in the audit report. If any exist, create a dedicated QA
verification epic FIRST (with `--priority=1` so it runs before fix epics). Include:
- The list of [NEEDS_QA] findings to verify
- Instruction to invoke the QA Engineer skill (`.claude/skills/compound/qa-engineer/SKILL.md`)
- The QA Engineer will start the dev server, perform browser automation (screenshots,
  exploratory testing, boundary inputs, accessibility, viewport stress), and produce
  a structured QA report with P0-P3 findings
The QA epic counts toward the overall epic budget below.

## Step 5: Create Improvement Epics
Group your improvements into well-structured epics (aim for 3-6 total, including the QA
epic from Step 4 if created). Each epic should:
- Have a clear, ambitious goal (not just "fix findings from reviewer X")
- Include specific acceptance criteria
- Cover a coherent bounded context (e.g., "security hardening", "error handling", "interaction polish", "performance")
- Mix reviewer findings WITH your own discoveries
- If the epic touches UI, include `browser_evidence` in the Verification Contract so the review phase invokes QA Engineer

For each epic:
```bash
bd create --title="Polish: <ambitious goal>" \
  --description="<what and why, acceptance criteria, specific files/areas>" \
  --type=epic --priority=2
```

Wire dependencies if needed: `bd dep add <dependent> <dependency>`

## Step 6: Output Epic IDs
After creating all epics, output each ID on its own line:
POLISH_EPIC: <epic-id>

ARCHITECT_HEADER_EOF
    echo "## Polish Report"
    cat "$report_file"
    echo ""
    echo "## Meta-Epic"
    echo "Parent: $META_EPIC"
    echo ""
    echo "## Spec File"
    echo "Read this file for product vision: $SPEC_FILE"
  } > "$prompt_file"

  claude --model "$MODEL" \
    --dangerously-skip-permissions \
    --permission-mode auto \
    --output-format text \
    --verbose \
    -p - < "$prompt_file" > "$architect_log" 2>"$cycle_dir/polish-architect.stderr" || true

  # Extract created epic IDs
  POLISH_EPICS=""
  while IFS= read -r line; do
    local epic_id
    epic_id=$(echo "$line" | sed 's/^POLISH_EPIC: //')
    if [ -n "$epic_id" ]; then
      POLISH_EPICS="$POLISH_EPICS $epic_id"
    fi
  done < <(grep "^POLISH_EPIC: " "$architect_log" 2>/dev/null || true)
  POLISH_EPICS="${POLISH_EPICS# }"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: polish architect created no epics"
  else
    log "Cycle $cycle_num: polish architect created epics: $POLISH_EPICS"
  fi
}

# --- Inner Loop ---
run_inner_loop() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: no epics to process -- skipping inner loop"
    return 0
  fi

  log "Cycle $cycle_num: generating inner infinity loop for epics: $POLISH_EPICS"

  local inner_script="$cycle_dir/inner-loop.sh"
  local epic_csv
  epic_csv=$(echo "$POLISH_EPICS" | tr ' ' ',')

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would run npx ca loop --epics $epic_csv"
    return 0
  fi

  npx ca loop --epics "$epic_csv" --model "$MODEL" --force -o "$inner_script" 2>"$cycle_dir/ca-loop-gen.stderr" || {
    log "ERROR: failed to generate inner loop script"
    return 1
  }

  log "Cycle $cycle_num: running inner infinity loop"
  bash "$inner_script" >"$cycle_dir/inner-loop.stdout" 2>"$cycle_dir/inner-loop.stderr" || {
    log "WARN: inner loop exited with non-zero status"
  }

  log "Cycle $cycle_num: inner loop completed"
}

# --- Main Loop ---
detect_polish_reviewers

log "Starting polish loop: $CYCLES cycles"
echo "{\"status\":\"running\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

POLISH_EPICS=""
POLISH_REPORT=""

for ((cycle=1; cycle<=CYCLES; cycle++)); do
  log "=== Cycle $cycle/$CYCLES ==="
  POLISH_EPICS=""
  POLISH_REPORT=""
  echo "{\"status\":\"running\",\"cycle\":$cycle,\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

  # Step 1: Audit
  run_polish_audit "$cycle"

  # Step 2: Synthesize
  synthesize_report "$cycle"

  # Step 3: Polish Architect
  if [ -n "$POLISH_REPORT" ]; then
    run_polish_architect "$cycle" "$POLISH_REPORT" || log "WARN: polish architect failed for cycle $cycle"
  else
    log "WARN: no polish report produced, skipping architect for cycle $cycle"
  fi

  # Step 4: Inner Loop
  run_inner_loop "$cycle"

  log "=== Cycle $cycle/$CYCLES complete ==="
done

# --- Post Loop ---
log "Polish loop completed: $CYCLES cycles"
echo "{\"status\":\"completed\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

# Commit and push results
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  log "Committing polish loop artifacts"
  git add docs/specs/polish-report-cycle-*.md agent_logs/.polish-status.json 2>/dev/null || true
  git commit -m "chore: polish loop cycle completion" 2>/dev/null || true
fi
if git remote get-url origin >/dev/null 2>&1; then
  log "Pushing results"
  git push 2>/dev/null || log "WARN: git push failed (non-fatal)"
fi

log "Done"
